# Generated by Django 4.1 on 2023-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=225)),
                ("details", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Work", "Work"),
                            ("Personal", "Personal"),
                            ("Family affair", "Family affair"),
                            ("Study", "Study"),
                        ],
                        default="None",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Done", "Done")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
